### ISSUE TITLE
What should philanthropy newsletter widget do?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#14]
We currently have a widget in the sidebar to subscribe to the philanthropy newsletter.  This doesn't actually do anything though.  
@OscarSiba what should this widget do?

**Comment by OscarSiba** [comment]
This newsletter was discontinued @maneesha. But I guess the subscribe widget would have [linked to this](https://carpentries.us14.list-manage.com/subscribe?u=46d7513c798c6bd41e5f58f4a&id=33f76196ac)?

**Comment by maneesha** [comment]
@OscarSiba Thanks for letting me know this was discontinued. Should this widget do something else?  It could be a link to our general newsletter page, or it could be a link to something else.

**Comment by OscarSiba** [comment]
Ok, please link it to our newsletter. Thanks @maneesha.

**Comment by maneesha** [comment]
Thanks.  Let's make it link direclty to the newsletter page (instead of a form action).

**Comment by AdamChlan** [comment]
@maneesha Is this something you want us to get in place? If so, assuming you want to have the title and the link managed outside of the theme?

**Comment by maneesha** [comment]
If we can remove this from being about the newsletter and make it instead any text and link, that would be great.  If that's the case, we should be sure to rename the widget.

If it needs to be static content, then it should say "Subscribe to our newsletter" and link to `/about-us/newsletter/`

**Comment by AdamChlan** [comment]
This has been simplified to just a be a button pointing to `/about-us/newsletter`

**Comment by maneesha** [comment]
Looks good.
