### ISSUE TITLE
Need 404 page layout

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#15]

**Comment by maneesha** [comment]
@AdamChlan can the layout include a text block we can customize?

**Comment by regisphilibert** [comment]
@maneesha a hugo theme's files can always be overwritten by the project's own files if using the same path. So by adding to your project's layouts directory a `404.html` you will ensure your project is using that rather than the theme's.

This is what the theme is using:

```
{{ define "main" }}
<div class="container px-5 pb-10 mx-auto">
  {{ partial "breadcrumbs" . }}

  <h1 class="text-[2rem] leading-[2.8125rem] font-semibold">404 Not Found</h1>
  <div class="prose">
    <p>The page you requested cannot be found.</p>
    <p>
      <a href="{{ .Site.Home.RelPermalink }}">
        Return to the home page
      </a>
    </p>
  </div>
</div>
{{ end }}
```

**Comment by maneesha** [comment]
That will work for us. Thanks.
