### ISSUE TITLE
Include intro text on workshops/lessons pages 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#16]
On pages that show a list of cards (like the workshops or lessons page), include an optional text block in the layout at the top of the page.

Edit to add that currently, if you add text to a page with a layout like `workshops` without any `H2` elements, the text does not display but an empty TOC is generated in sidebar.  Does this code in the sidebar layout mean that if `toc: false` is in the page frontmatter that the TOC should not display? That does not seem to work in this case.

**Comment by AdamChlan** [comment]
@maneesha you should use `hideToc: true` to hide the TOC. I tested this and it works as expected on this template.

**Comment by maneesha** [comment]
Thanks for the info about `hideToc`.
We should still have the text block on the page.

**Comment by maneesha** [comment]
Looks good!
