### ISSUE TITLE
Can pages included mixed HTML/markdown content? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#21]
Include fontawesome in theme so we can use icons throughout sites.

**Comment by AdamChlan** [comment]
@maneesha Sure, please share the script to include and we can get it integrated.

**Comment by maneesha** [comment]
Sorry - I thought I had put the code here when I removed the "Awaiting Client Feedback" label yesterday.  

```
# Include fontawesome
<script src="https://kit.fontawesome.com/3a6fac633d.js" crossorigin="anonymous"></script>
```

**Comment by AdamChlan** [comment]
@maneesha this has been added

**Comment by maneesha** [comment]
@AdamChlan I am trying to do some troubleshooting so I wanted to ask you -  Do you know of anything in the theme that would make fontawesome not always work? 

Here is an example of where it works: [source](https://github.com/carpentries/new-website/pull/37/files) and [rendered page](https://deploy-preview-37--carp-new-website.netlify.app/about-us/careers/)
Here is an example of where it does not: [source](https://github.com/swcarpentry/new-website/pull/21/files) and [rendered page](https://deploy-preview-21--swc-new-website.netlify.app/lessons/)

Hugo theme is up to date in both instances.  There are no domain restrictions on our fontawesome kit.

**Comment by maneesha** [comment]
@AdamChlan If there is anything you can easily think of that may cause this, please let me know.  Otherwise we can close this issue.

**Comment by regisphilibert** [comment]
I think this is related to https://github.com/carpentries/carpentries-hugo-theme/issues/23#issuecomment-2331589299

**Comment by maneesha** [comment]
Digging into this more, it does not seem to have anything to do with fontawesome or whether the theme is updated.  Instead, HTML content is being ignored entirely.  Looking at examples above of where it works and does not -- on the SWC site where it does not work, the browser inspector reveals that **all** HTML content is being ignored.

![image](https://github.com/user-attachments/assets/49b11486-64f7-479f-9025-52de13d9cd3e)

From some reading, it looks like to have mixed HTML/markdown content, we need to set 

```
[markup]
  [markup.goldmark.renderer]
    unsafe=true
```

However, this doesn't explain why it works in one page/site and not another.  
We are using the same theme version and same layout on both.

@AdamChlan @regisphilibert Do you have any ideas of why this may be happening?

**Comment by maneesha** [comment]
Renaming issue because it is about the theme functioning consistently and correctly, and not about fontawesome.

**Comment by regisphilibert** [comment]
Is the `unsafe: true` setting used on both sites/branches etc... ?

**Comment by maneesha** [comment]
This did it - thank you!
