### ISSUE TITLE
How is site-wide search implemented? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#22]
See notes in this issue: https://github.com/carpentries/tnd-carpentries-working/issues/40

**Comment by regisphilibert** [comment]
Via google as discussed. (commit here: https://github.com/carpentries/tnd-carpentries-working/pull/43/files)

https://carp-new-website.netlify.app/search/

**Comment by maneesha** [comment]
Opening this back up to see if there is a way to test the search (as Google doesn't seem to index netlify pages).

**Comment by regisphilibert** [comment]
You can update this line on the theme with an indexed url: 

https://github.com/carpentries/carpentries-hugo-theme/blob/44ca2d5ecccec500e498c493956e50c4d7f25d28/layouts/shortcodes/search.html#L1
