### ISSUE TITLE
Set up RSS feed for blog.

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#24]
We need an RSS feed for the blog.

**Comment by maneesha** [comment]
@AdamChlan We should be able to get the raw feed from `/blog/index.xml`, correct? Is the "out of scope" part styling it? 
Can the raw feed be customized in any way?

**Comment by AdamChlan** [comment]
@maneesha I'll look to get a basic feed in place

**Comment by maneesha** [comment]
Removing the "out of scope" label as it's noted above we can get a basic feed in place.  Would the basic feed be more than the automatically generated `/blog/index.xml`?

No additional styling or services are needed now.

**Comment by AdamChlan** [comment]
@maneesha the templates now include a reference to the RSS feed. It's nothing more than the automatically generated feed.

**Comment by maneesha** [comment]
Thanks!
