### ISSUE TITLE
How does Hugo handle sections without _index or index file? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#25]
Example [Carpentries site](https://carp-new-website.netlify.app/) build from [this repo](https://github.com/carpentries/new-website).

Some folders have an `_index.md` file.  Some folders do not, but an index page gets generated anyways.

Example: `workshops` folder has `_index.md`.  As expected, this renders to [this page](https://carp-new-website.netlify.app/workshops/).
However, `host` folder does not have an index page, and it renders to a blank page called [Hosts (plural)](https://carp-new-website.netlify.app/host/).

**Comment by regisphilibert** [comment]
By default, any root folder beneath `/content` with children md is considered a section and generate a landing page for that section. Title is infered from the directory name. (by pluralizing it)

Adding a `_index.md` in the folder allow to add some front-matter information to the section's landing page, like your own title for example.

**Comment by maneesha** [comment]
@regisphilibert is it possible to disable that behavior so a landing page is not automatically generated?

**Comment by regisphilibert** [comment]
You're going to have to create a `_index.md` in the concerned directory with the following:

```
_build:
  render: never
  list: never
```

**Comment by maneesha** [comment]
Thanks!
