### ISSUE TITLE
Consistent version of go

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#27]
The theme's [go.mod](https://github.com/carpentries/carpentries-hugo-theme/blob/main/go.mod) file uses 1.18.

The netlify.toml file we've been using uses 1.14.

What version should we be using?

**Comment by maneesha** [comment]
@regisphilibert note also that the [latest version](https://go.dev/learn/) is 1.23.

**Comment by maneesha** [comment]
Assigning back to @regisphilibert for guidance on the newest version.

**Comment by AdamChlan** [comment]
Information has been added to the readme

**Comment by maneesha** [comment]
Thanks @AdamChlan 
Can you share why we should not be using the most current version of go?

**Comment by regisphilibert** [comment]
As we cannot commit to having this project work with every new version of Go or Hugo, we're sticking with the version we built it with. You can upgrade, we just can't garantee our work beyond that. See theme's `hugo.yaml`'s `module.minVersion` for Hugo for example.

**Comment by maneesha** [comment]
Thanks for sharing this @regisphilibert.  Is there a reason you chose that version of go? This will help us plan what our future needs may be.

**Comment by regisphilibert** [comment]
No particular reason @maneesha.
