### ISSUE TITLE
All widgets should use the same text size 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#29]
For example, [feedback](https://github.com/carpentries/carpentries-hugo-theme/blob/main/layouts/partials/widgets/feedback.html) and [meta](https://github.com/carpentries/carpentries-hugo-theme/blob/main/layouts/partials/widgets/meta.html) use `text-xs` while [edit-github](https://github.com/carpentries/carpentries-hugo-theme/blob/main/layouts/partials/widgets/edit-github.html) and [sponsors](https://github.com/carpentries/carpentries-hugo-theme/blob/main/layouts/partials/widgets/sponsors.html) use `text-sm`.

**Comment by regisphilibert** [comment]
What size do you prefer?

**Comment by maneesha** [comment]
text-sm

**Comment by maneesha** [comment]
Thanks @AdamChlan.  Looks good (aside from the issue with the meta widget #12).  I'm closing this issue, assuming that widget will render to the same size when it is fixed.
