### ISSUE TITLE
Testing theme from a branch

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#33]
The README now includes instructions on how to [test changes to the theme locally](how to test theme if we make changes on a branch) by replacing the theme on GH with a local path.

Is it possible to also use a branch other than `main` on GH?

**Comment by regisphilibert** [comment]
You mean from the GitHub website? I can't say.

**Comment by maneesha** [comment]
@AdamChlan Yes, that's what I was wondering about. When I use this theme in a project [like here](https://github.com/swcarpentry/new-website/blob/main/go.mod#L5), it looks like it always uses the `main` branch.  Is it possible to test a build from another branch?

**Comment by maneesha** [comment]
Removing "Ready for Review" label, noting my question above.

**Comment by maneesha** [comment]
@AdamChlan @regisphilibert If either of you know this easily, please let me know. Otherwise we can close this issue.

**Comment by regisphilibert** [comment]
I'm sure it's possible but do not know how.
