### ISSUE TITLE
Workshops filter should include inperson & online for delivery options

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#34]
In an earlier prototype of the [workshop search page](https://carpentries.netlify.app/workshops/past-workshops/) we see "inperson" and "online" as options for "Filter by Delivery."

In sites we have recently built with the theme, we only see "Online" as an option.  See for example [Carpentries workshops](https://carp-new-website.netlify.app/workshops/past-workshops/) and [Software Carpentry workshops](https://swc-new-website.netlify.app/workshops/workshops-past/).

**Comment by regisphilibert** [comment]
@maneesha thank you for reporting that, a oversight from our recent refactoring of the filter/data parsing. This is fixed on the main branch of the theme. You should update your projects to latest version of the theme.

**Comment by maneesha** [comment]
Looks good.
