### ISSUE TITLE
Generic gravatar if someone does not have a Github id

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#37]
For person profiles, we use the individual's Github profile pic.  If a person does not have a github id recorded, we should use a generic avatar. Currently, no image is displayed at all ([see example](https://carp-new-website.netlify.app/community/instructors/)).

See the [current implementation](https://github.com/carpentries/carpentries.org/blob/main/_includes/community_profiles.md?plain=1#L13) of using a generic avatar.

**Comment by maneesha** [comment]
I don't think this should be out of scope as it is part of the current  design that this was based off of.  

I think we could implement this by adding a conditional to [this block](https://github.com/carpentries/carpentries-hugo-theme/blob/main/layouts/partials/func/ParsePerson.html#L83).  In pseudocode: `if github, use github image; else use https://www.gravatar.com/avatar/<person_name>?d=mp`

@regisphilibert  Would that work?

**Comment by regisphilibert** [comment]
I've added your suggested implementation. All github-less users all a generic gravatar, so not great to test. But it aligns with your current website so I guess it's 👌 

You can update the theme on your projects.

**Comment by maneesha** [comment]
Yes, this would result in a generic image for everyone without Github.  Looks good.
