### ISSUE TITLE
"opengraph" param?

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#38]
In setting up the Carpentries site using this theme, @regisphilibert set up the [following param](https://github.com/carpentries/new-website/blame/main/config/_default/params.yaml): 

```
images:
- thearpentries-opengraph.png
```

Typo aside, opening this issue to see what this should have been and how we should have been using it.

**Comment by regisphilibert** [comment]
We're relying on Hugo's embedded [Open Graph ](https://gohugo.io/templates/embedded/#open-graph)template and it looks at this parameter for the default SEO image of the site. (Used for pages without a frontmatter image).

**Comment by maneesha** [comment]
Thanks!
