### ISSUE TITLE
Customize text color on hero image

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#4]
Text color on hero image should be customizable (at least black or white) so we can choose a color that contrasts enough with the background image.

**Comment by maneesha** [comment]
@AdamChlan Can you share where we set the text color?

**Comment by AdamChlan** [comment]
@maneesha here you can see where it is set:

https://github.com/carpentries/new-website/pull/1/files#diff-200abda264c3530e9cdb5d895e25d50bc3ed567079b39fe2ee3c1d1b5d661e09

**Comment by maneesha** [comment]
Looks good!
