### ISSUE TITLE
Flags should go in theme 

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#6]
[Flags](https://github.com/carpentries/new-website/tree/main/assets/files/flags) should go in theme as we will always want access to them.

**Comment by maneesha** [comment]
I opened this issue here because I saw them in the `assets` folder of the new website (https://github.com/carpentries/new-website/tree/main/assets/files/flags) but now I see they are also in the theme (https://github.com/carpentries/carpentries-hugo-theme/tree/main/assets/flags).
However, they do not render in a local build.  See screenshot and [link to PR](https://github.com/swcarpentry/new-website/pull/2).

![image](https://github.com/user-attachments/assets/7c66791d-e5dc-40a4-904d-0ce75e677da6)

**Comment by AdamChlan** [comment]
@maneesha is this still an issue for you? it's looking good to me locally and on your preview link

**Comment by maneesha** [comment]
Flags are not consistently rendering correctly. See for example [Software Carpentry workshops](https://swc-new-website.netlify.app/workshops/workshops-past/).

**Comment by regisphilibert** [comment]
@AdamChlan our theme is loading png files, but the `GetTaxonomyMapping` function is pointing to SVG (l:71), I think we might have left a `/static/flags/` directory in the `new-site` project with svgs in it. So it works there. 

We should update the GetTaxonomyMapping to use png and remove the `/static/flags` directory from the new-site repo.

**Comment by AdamChlan** [comment]
function updated to png @maneesha ready for you to review

**Comment by maneesha** [comment]
Looks good.
