### ISSUE TITLE
deprecated feature?  (data.GetJSON)

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#7]
Note that local build gives this warning.  `data.GetJSON` does not seem to be used anywhere in this theme; leaving a note here to be sure.  

`WARN  deprecated: data.GetJSON was deprecated in Hugo v0.123.0 and will be removed in a future release. use resources.Get or resources.GetRemote with transform.Unmarshal.`

**Comment by AdamChlan** [comment]
@maneesha confirming we are not using this so will close this out.
