### ISSUE TITLE
Workshops page should take frontmatter param to filter by lesson program

### ISSUE THREAD

**Issue by maneesha** [carpentries/carpentries-hugo-theme#9]
Similar to #8, when the workshops layout is used, we should be able to define lesson_program in the page's frontmatter.

If lesson_program is undefined, it should use all items from lessons.yaml.
If lesson_program is defined, the filter for lesson_program should not display. (note unlike for lessons, we don't need a filter for the lesson program because our source data is already filtered accordingly.)

**Comment by maneesha** [comment]
@AdamChlan Can you share an example of what the frontmatter param should look like?

**Comment by AdamChlan** [comment]
Sure, it would look like: 

`lesson_program: 'SWC'`

It's the values that appear in the lessons.yaml file in the project.

**Comment by maneesha** [comment]
Looks good.
